### ISSUE TITLE
Naming files

### ISSUE THREAD

**Issue by Pierstoval** [knpuniversity/phpstorm-settings#1]
Hi guys, this project will be awesome :smile: 

What about renaming the different files by prepending `knp_` to avoid conflicts for actual configs?
I personally have templates for Symfony inside a `symfony.xml` file, so having them inside a `knp_symfony.xml` file would resolve the potential conflicts, and more, allow to unzip the whole project right inside the `WebIde**` directory.

What do you think about this? :)

**Comment by weaverryan** [comment]
Good idea! :+1:

**Comment by TomasVotruba** [comment]
Shall I send PR?

**Comment by weaverryan** [comment]
That would be perfect :)

**Comment by TomasVotruba** [comment]
Done :)
