### ISSUE TITLE
Missing context for "createquery"

### ISSUE THREAD

**Issue by fab01** [knpuniversity/phpstorm-settings#17]
Hi,

I noticed that **createquery** shortcode doesn't work.
As a temporary fix I put context tag in <template name="createquery"...
 
```
<context>
  <option name="PHP" value="true" />
</context>
```

Now seems ok.
Did someone else got the same problem?

Cheers :)

**Comment by weaverryan** [comment]
You're absolutely right! I've just fixed it - thanks!
